# Generated by Django 3.2.9 on 2021-12-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211224_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brandname',
            new_name='username',
        ),
    ]
