# Generated by Django 3.2.9 on 2021-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='percent_rating',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_features',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('c', 'Checking')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
