# Generated by Django 3.2.9 on 2021-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.CharField(max_length=10),
        ),
    ]
