# Generated by Django 3.2.9 on 2021-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
