# Generated by Django 3.2.9 on 2021-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('c', 'Checking')], default='c', max_length=1, null=True),
        ),
    ]
