# Generated by Django 3.2.9 on 2021-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211204_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.BooleanField(default=True),
        ),
    ]
