# Generated by Django 3.2.9 on 2021-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='publish_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='publish_status',
            field=models.BooleanField(default=True),
        ),
    ]
